### ISSUE TITLE
При применении манифестов возникает ошибка

### ISSUE THREAD

**Issue by SablinIgor** [express42/otus-platform-tests#1]
+kubectl apply -f kubernetes-volumes/minio-headless-service.yaml kubernetes-volumes/minio-statefulset.yaml
error: Unexpected args: [kubernetes-volumes/minio-statefulset.yaml]

Предлагается убрать звездочку в файле 
/2019-06/homeworks/kubernetes-volumes/run.sh

kubectl apply -f kubernetes-volumes/*

**Comment by dmitriy-kharchenko** [comment]
Спасибо за ревью наших тестов) Исправили)
